### ISSUE TITLE
Curseforge Modpack Licensing

### ISSUE THREAD

**Issue by crackscout123** [JosiahFu/ToolTrimsMod#1]
Can you add license coverage for CurseForge projects!? Curse got a wider range of Mods and this mod is the only mod in my 250 Mods Modpack that is causing that I cant publish it. Weeks of work is now just falling apart. I considered switching the entire pack to Modrinth but guess what that makes it even worse because many mods Arent even available on Modrinth.
I'll give you credits on the Modpack Page if you want me to do, thats not a problem at all but please help me out here bro

**Comment by JosiahFu** [comment]
I don't mind it on the code side, but the art assets belong to JoeFly. I'll contact them and see if they're okay with it.

**Comment by JosiahFu** [comment]
Yes, we're fine with it. Does curseforge allow embedding the file directly or do we need to create a curseforge project?

**Comment by PokeSantiTW** [comment]
Thank you sooo much! Love this mod ❤️

**Comment by ThePotatoArchivist** [comment]
It hasn't been approved yet because it includes the word "mod" in the name lol, I'm contacting support about it

**Comment by ThePotatoArchivist** [comment]
It's been approved, here you go!
https://www.curseforge.com/minecraft/mc-mods/tool-trims-mod/
